name: zeroae-goblet-dev
channels:
  - zeroae
  - conda-forge
  - defaults
dependencies:
  - ipython
  - python
  - pip

  # Setup Requirements (setup.py:setup_requirements)
  - pytest-runner >=5
  - setuptools_scm
  - wheel

  # Install Requirements (setup.py:requirements)
  - chalice >=1.13
  - click >=7.0
  - click-plugins
  - click-log
  - entrypoints
  - environs
  - jinja2 >=2.9,<3
  - octokitpy >=0.13.0,<0.14
  - pypubsub >=4.0.3,<5
  - python-dateutil

  # Test Requirements (setup.py:test_requirements)
  - pytest >=3
  - pytest-chalice
  - pytest-cov
  - requests-mock

  # Documentation Requirements
  - sphinx
  - watchdog

  # Dev Workflow requirements
  - pre-commit
  - black
  - flake8
  - rsa
  - twine
